on:
  pull_request:
    types: [opened, reopened]

name: notification-pr-open
jobs:
  slack_msg_send:
    if: github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    steps:
    - name: Post to a Slack channel
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
      # Slack channel id, channel name, or user id to post message.
      # See also: https://api.slack.com/methods/chat.postMessage#channels
        # For posting a rich message using Block Kit
        payload: |
          {
            "text": "A PR has been created:\n URL of the PR: ${{ github.event.pull_request.html_url }}, Target Branch- ${{ github.event.pull_request.base.ref }}\n PR Title- ${{ github.event.pull_request.title }}, Requested By: ${{ github.event.pull_request.user.login }}" }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
